site_name: "LinkML Documentation for Proposed MIxS 6.2"
theme:
  name: material
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  - MIxS Documentation: index.md

site_url: https://turbomam.github.io/mixs-envo-struct-knowl-extraction
repo_url: https://github.com/turbomam/mixs-envo-struct-knowl-extraction

docs_dir: mixs-docs-md
