name: proposed_mixs_6_term_attribute_replacements_schema
id: http://example.com/proposed_mixs_6_term_attribute_replacements_schema
imports:
  - linkml:types
prefixes:
  linkml: http://example.com/GSC_MIxS_6/
slots:
  host_occupation:
    range: string
    comments:
      - "Couldn't convert host_occupation with value veterinary to integer"
      - almost all host_occupation values in the NCBI biosample_set are strings, not integers
  api:
    examples:
      - value: 31.1 API
        description: "from slot's description"
  basin:
    examples:
      - value: Campos
        description: "from slot's description"
  coll_site_geo_feat:
    examples:
      - value: "farm [ENVO:00000078]"
        description: present in NCBI biosample_set
  collection_date:
    examples:
      - value: 2023-01-15T00:00:00
        description: arbitrarily selected ISO 8601 date
  env_broad_scale:
    examples:
      - value: rangeland biome [ENVO:01000247]
        description: arbitrarily selected biome
    multivalued: false
  env_local_scale:
    examples:
      - value: hillside [ENVO:01000333]
        description: arbitrarily selected landmark
    multivalued: false
  env_medium:
    examples:
      - value: bluegrass field soil [ENVO:00005789]
        description: arbitrarily selected environmental medium
    multivalued: false
  iwf:
    range: float
    examples:
      - value: 0.79
        description: casual Google search
    comments:
      - percent or float?
      - pattern was "[0-9]*\\.?[0-9]+ ?%"
  micro_biomass_meth:
    examples:
      - value: http://dx.doi.org/10.1016/j.soilbio.2005.01.021
        description: present in NCBI biosample_set
    comments:
      - slot name/scn was microbial_biomass_meth
  occup_density_samp:
    examples:
      - value: 0.1
        description: casual Google search for legislation about occupants per square foot
  carb_nitro_ratio:
    range: float
    pattern: ""
  occup_samp:
    range: float
    pattern: ""
  ferm_rel_humidity:
    pattern: "[0-9]*\\.?[0-9]+ ?%"
    comments:
      - percent or float?
    examples:
      - value: 95%
        description: removed " RH" suffix from XLSX example
  rel_air_humidity:
    range: float
    comments:
      - percent or float?
  season_humidity:
    range: float
    comments:
      - percent or float?
  surf_humidity:
    range: float
    comments:
      - percent or float?
  water_cut:
    examples:
      - value: 45%
        description: casual Google search for water cut
    pattern: "[0-9]*\\.?[0-9]+ ?%"
    comments:
      - percent or float?
  time_last_toothbrush:
    comments:
      - problematic ISO 8601 period validation
      - P2H45M does not match ^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d+[HMS])(\\d+H)?(\\d+M)?(\\d+S)?)?$
    examples:
      - value: PT2H45M
        description: "from slot's description"
  #  samp_transport_dur:
  #    comments:
  #      - "{float} {unit} or period?"
  #      - problematic ISO 8601 period validation
  #      - P10D does not match ^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d+[HMS])(\\d+H)?(\\d+M)?(\\d+S)?)?$
  #  #    examples:
  #  #      - value: 10 days
  #  #        description: converted slot's ISO 8601 period to a measurement value string
  season:
    comments:
      - autumn [NCIT:C94733] does not match ^\\S+.*\\S+ \\[[a-zA-Z]{2,}:\\d+\\]$
      - would require ^\\S+.*\\S+ \\[[a-zA-Z]{2,}:[a-zA-Z0-9]\\]$
    pattern: ^\S+.*\S+ \[[a-zA-Z]{2,}:[a-zA-Z0-9]+\]$
  host_body_product:
    examples:
      - value: mucus [FMA:66938]
        description: reformatted the example from the XLSX file, "Portion of mucus [fma66938]"
  photosynt_activ:
    examples:
      - value: 0.1 mol CO2 m-2 s-1
        description: added a magnitude to the example from the XLSX file, " mol CO2 m-2 s-1"
  animal_am_freq:
    range: float
    pattern: ""
    examples:
      - value: 1.5
        description: completely made up
  built_struc_age:
    examples:
      - value: 15 years
        description: completely made up
  food_source_age:
    comments:
      - ISO 8601 period or measurement value?
    examples:
      - value: 6 months
        description: converted slot's ISO 8601 period to a measurement value string
  study_inc_dur:
    examples:
      - value: PT24H
        description: provided example of P24H may not satisfy strict ISO 8601 period validation
  timepoint:
    examples:
      - value: PT24H
        description: provided example of P24H may not satisfy strict ISO 8601 period validation
